offchain:
    # set httpsignature public keys for the endpoints
    public_keys:
      - id: "key1"
        key: "abf9649d7a0a7534cde49f12de47effd601e60a2258e51b5a257af9ef78e901f"
    # optionally, set bearer tokens for the read endpoints (not relevant for write endpoints)
    bearer_tokens:
      - id: "token1"
        token: "raw:1234567890"

  # setup API keys for the exchanges
  exchanges:
    okx:
      # load from env
      api_key: "env:OKX_API_KEY"
      secret_key: "env:OKX_API_SECRET"
      passphrase: "env:OKX_API_PASSPHRASE"
    bybit:
      # load from your favorite secret manager
      api_key: "gcp:your_gcp_project,API_KEY_NAME"
      secret_key: "gcp:your_gcp_project,API_SECRET_NAME"
    binance:
      # more concise, load multiple secrets either in JSON or separated by newlines
      # E.g. `{"api_key": "...", "secret_key": "..."}`
      secrets: "gcp:your_gcp_project,SECRETS_NAME"
    binanceus:
      secrets: "gcp:your_gcp_project,SECRETS_NAME"
