name: Test Offchain
on:
  push:
    branches:
      - "**"
jobs:
  test:
    name: "Test offchain"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - run: sudo apt-get install -y just
      - run: just lint test
